CREATE TABLE BOOK(
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    AUTHOR VARCHAR2(20) NOT NULL,
    PUBLISHER VARCHAR2(20) NOT NULL,
    PUBLISH_DATE DATE NOT NULL,
    PRICE NUMBER NOT NULL
);
COMMENT ON COLUMN BOOK.BOOK_ID
IS '책번호';
COMMENT ON COLUMN BOOK.TITLE
IS '책제목';
COMMENT ON COLUMN BOOK.AUTHOR
IS '저자명';
COMMENT ON COLUMN BOOK.PUBLISHER
IS '출판사';
COMMENT ON COLUMN BOOK.PUBLISH_DATE
IS '출판날짜';
COMMENT ON COLUMN BOOK.PRICE
IS '가격';

CREATE SEQUENCE seq_bid
INCREMENT BY 1
START WITH 1
NOCYCLE
NOCACHE
NOORDER;

INSERT INTO BOOK
VALUES(seq_bid.NEXTVAL, '천로역정','존 번연','CUP',TO_DATE('2024.02.02', 'RRRR.MM.DD'), '24300');

INSERT INTO BOOK
VALUES(seq_bid.NEXTVAL, '서울 보통 시','하상욱','아르테',TO_DATE('2024.01.24', 'RRRR.MM.DD'), '15390');

INSERT INTO BOOK
VALUES(seq_bid.NEXTVAL, '슬퍼하지 말아요, 곧 밤이 옵니다','헤르만헤세','나무생각',TO_DATE('2024.01.20', 'RRRR.MM.DD'), '16930');

INSERT INTO BOOK
VALUES(seq_bid.NEXTVAL, '특수청소부','나카야마','블루홀식스',TO_DATE('2024.02.14', 'RRRR.MM.DD'), '14370');

INSERT INTO BOOK
VALUES(seq_bid.NEXTVAL, '사라진 것들','앤드루 포터','문학동네',TO_DATE('2024.01.15', 'RRRR.MM.DD'), '16200');

COMMIT;




